# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1

In [3]:
import numpy as np
n=10
Numpyarray=np.arange(1,n+1)
print(Numpyarray)

[ 1  2  3  4  5  6  7  8  9 10]


```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2

In [19]:
Zeromatrix=np.zeros((3,3))
print(Zeromatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3

In [21]:
Lins=np.linspace(0,5,10)
print(Lins)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4

In [29]:
idmatrix=np.eye(5)
print(idmatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5

In [46]:
np.random.seed(10)
mat=np.random.random(((4,4)))
print(mat)
help(np.random.random)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]
Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [48]:
np.random.seed(0)
mat=np.random.random(((4,4)))
print(mat)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6

```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7

In [56]:
A=np.arange(1,17)
print(A)
A.reshape((4,4))
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8

In [59]:
A.dtype

dtype('int32')

```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9

In [67]:
B=np.arange(2,101,2)
print(B)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10

In [79]:
C=np.random.randint(10,50,(6,6))
print(C)

[[48 21 28 37 10 24]
 [45 22 30 21 14 16]
 [14 13 22 46 24 25]
 [30 45 33 25 23 31]
 [15 45 10 41 15 40]
 [10 46 44 39 13 44]]


```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11

In [89]:
D=np.array([[1,2,3,4],[2,3,4,5],[4,2,6,7]])
print(D)
E=D[1:3,:]
print('========================\n')
print(E)
print('========================\n')
F=D[1:3,1:3]
print(F)

[[1 2 3 4]
 [2 3 4 5]
 [4 2 6 7]]

[[2 3 4 5]
 [4 2 6 7]]

[[3 4]
 [2 6]]


```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12

In [93]:
Sum=np.sum(D)
print(Sum)

43


```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13

In [103]:
Mean=np.mean(B)
print(Mean)
print('========================\n')
Median=np.median(B)
print(Median)
print('========================\n')
Standard_dev=np.std(B)
print(Standard_dev)

51.0

51.0

28.861739379323623


```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14

In [105]:
Max=np.max(D)
print(Max)
print('========================\n')
Min=np.min(D)
print(Min)
print('========================\n')

7

1



```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15

In [139]:
mat=np.random.randint(0,20,(4,5))
print(mat)

[[ 6  9 15  3 19]
 [12 18 17 10  2]
 [ 1 11  3 12  4]
 [ 1 17  0  7  4]]


In [149]:
print(np.argmax(mat, axis=1))

[4 1 3 1]


In [151]:
#help(np.argmax)

```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16

In [165]:
G=np.arange(1,11)
#print(G)
#G=G[::-1]
print(G)
np.flip(G)

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17

In [169]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[2,3,4],[1,5,3],[5,6,7]])
prodmat=mat1*mat2
print(prodmat)

[[ 2  6 12]
 [ 4 25 18]
 [35 48 63]]


```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18

In [173]:
Diag=np.diag(np.arange(1,5))
print(Diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19

In [177]:
result=mat1.dot(mat2)
print(result)

[[ 19  31  31]
 [ 43  73  73]
 [ 67 115 115]]


```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20

In [185]:
resmat=result.flatten()
print(resmat)

[ 19  31  31  43  73  73  67 115 115]


```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21

In [193]:
v1=np.array([2,3,4])
v2=np.array([1,3,5])
v3=np.vstack((v1,v2))
print(v3)

[[2 3 4]
 [1 3 5]]


```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22

In [197]:
v4=np.hstack((v1,v2))
print(v4)

[2 3 4 1 3 5]


```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23

In [217]:
array1=np.arange(6)
''' This split array into multiples sub arrays of equal size'''
array1_splt=np.split(array1,3)
print('==================\n')
print(array1_splt)
''' This split array into multiples sub arrays of unequal size'''
array1=np.arange(7)
array2_splt=np.array_split(array1,4)
print('==================\n')
print(array2_splt)


[array([0, 1]), array([2, 3]), array([4, 5])]

[array([0, 1]), array([2, 3]), array([4, 5]), array([6])]


```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24

In [227]:
Array=np.round(np.random.random(10),2)
print(Array)

[0.28 0.13 0.39 0.96 0.19 0.9  0.54 0.46 0.88 0.46]


```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25

In [233]:
# Finding a unique element of a given Numpy array
data=np.array([2,3,3,4,5,6,7,7,8,4,9])
Unique=np.unique(data)
print(Unique)

[2 3 4 5 6 7 8 9]


```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26

In [247]:
data[data<4]=4
print(data)

[4 4 4 4 5 6 7 7 8 4 9]


```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27

In [249]:
Data=np.arange(1,21)
res=np.cumsum(Data)
print(res)

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


In [253]:
#help(np.cumsum)

```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28

In [271]:
h=np.eye(9)
Nz=np.count_nonzero(h)
print(Nz)

9


In [273]:
#help(np.count_nonzero)

```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29

In [281]:
M=np.random.random(10)
#print(M)
SortM=np.sort(M)
print(SortM)

[0.45722345 0.45813883 0.57575116 0.59098417 0.79639147 0.82076712
 0.85772264 0.90884372 0.95187448 0.9591666 ]


In [277]:
#help(np.sort)

```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30

In [285]:
Mat=np.array([[2,4,6],[1,7,3],[9,6,5]])
row_sum=np.sum(Mat,axis=1)
print(f'row-wise sum: {row_sum}')
print('======================\n')
col_sum=np.sum(Mat,axis=0)
print(f'column-wise sum: {col_sum}')

row-wise sum: [12 11 20]

column-wise sum: [12 17 14]


```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31

In [329]:
Array=np.random.randint(1,5,size=(3,4))
#print(Array)
normalized_Array=(Array-np.min(Array))/(np.max(Array)-np.min(Array))
print(normalized_Array)

[[0.33333333 1.         0.         0.66666667]
 [0.33333333 0.66666667 1.         0.33333333]
 [0.66666667 0.         0.66666667 0.        ]]


```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32

In [333]:
v1=np.array([1,2,4,5,6])
v2=np.array([3,4,5,7,8])
v=np.dot(v1,v2)
print(v)

114


```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33

In [337]:
Mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
Tr=np.trace(Mat)
print(Tr)

15


```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34

In [339]:
Mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
Mat_swap=np.transpose(Mat)
print(Mat_swap)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35

In [343]:
Array=np.array([1,2,3,4,5])
col_vec=Array.reshape(-1,1)
print(col_vec)

[[1]
 [2]
 [3]
 [4]
 [5]]


```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---